name: Create and publish docker image
on:
  push:
    branches: branch_for_docker
  permissions:
      contents: read
      packages: write
      attestations: write
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: file_with_plot
jobs:
  build_and_push_image:
    runs_on: macos-latest
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3
  - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}