name: Create and publish a Docker image

on:
  push:
    branches:
      - 'branch_for_docker'
env:
  TEST_TAG: /usr/src/app:test_sorting

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image 
        run: docker build -t plot_line .
      - name: Run tests inside the container
        run: docker run test_sorting run pytest
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: anastasiiadenysenko/modern-methods-of-software-development-uni:latest
