name: Create and publish a Docker image

on:
  push:
    branches:
      - 'branch_for_docker'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build . --tag ghcr.io/anastasiia-denysenko/plot_line:v1
      
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/anastasiia-denysenko/plot_line:v1

      - name: Build Docker image (test)
        run: docker build -t ghcr.io/anastasiia-denysenko/plot_line_test:v1 -f Dockerfile.test .

      - name: Push test Docker image to GitHub Container Registry
        run: docker push ghcr.io/anastasiia-denysenko/plot_line_test:v1

      - name: Run tests in Docker container
        run: docker run ghcr.io/anastasiia-denysenko/plot_line_test:v1
