name: Docker image for localstack app

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image 
        working-directory: ./terraform
        run: docker-compose up -d --build
      - name: Set up tflocal
        run: pip install terraform-local
      - name: Init terraform
        working-directory: ./terraform
        run: tflocal init
      - name: Plan terraform
        working-directory: ./terraform
        run: tflocal plan
      - name: Apply terraform
        working-directory: ./terraform
        run: tflocal apply --auto-approve
