name: Test x and ref

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: test x_and_ref
      run: lab_4\test_x_and_ref.cpp
