name: Test x and ref

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Setup:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc
    
    steps:
    - uses: actions/checkout@v2
    - name: run main
      run: lab_4\main.cpp
