name: Test x and ref

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: compile tests
      run: make test CXX=g++
    - name: run main
      run: make lab_4\main.cpp
    - name: run a.exe
      run: make lab_4\a.exe
